spring:
  application:
    name: apple-device-service

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3309/apple_device_service
  jpa:
    hibernate:
      ddl-auto: none

app:
  service:
    cors:
      baseUrl: http://localhost:3000
      allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
  security:
    jwt:
      secret: JHD2p1EolyuH3K6Gjz05onMO5hRT8CYHJHD2p1EolyuH3K6Gjz05onMO5hRT8CYH
      expiration: 86400000
      header: Authorization
      prefix: Bearer