spring:
  application:
    name: apple-device-service

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3309/apple_device_service
  jpa:
    hibernate:
      ddl-auto: none